---
title: "EDA of second client"
author: "Haochen Pan"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1 : General view about RecaptchaScore, Score and questions about identity

### Preparation

```{r}
library(readr)
PESedit_1 <- read_csv("D:/MSSP/PESedit 1.csv")
P1 <- PESedit_1[c("ResponseId","Q_RecaptchaScore","SC0","Q4","Q5","Q6","Q7","Q8","Q9","Q10","Q11","Q12","Q13","Q14","Q15","Duration")]
```


```{r}
P2 <- P1[-c(2,1),]
P2
P2$SC0 <- as.integer(P2$SC0)
```

### The RecatchaScore for 200+ responses
```{r}
library(ggplot2)
ggplot(data = P2, mapping = aes(x = ResponseId, y = Q_RecaptchaScore)) +
  geom_point(size = 0.3, color = "blue", alpha = 0.8) +
   scale_x_discrete(breaks = seq(0, 100, by = 5)) 
```
### 
```{r}
ggplot(data = P2) +
   geom_bar(mapping = aes(x = Q_RecaptchaScore))
```
### The Score for 200+ responses
```{r}
ggplot(data = P2) +
   geom_bar(mapping = aes(x = SC0))
```



```{r}
ggplot(data = P2, mapping = aes(x = ResponseId, y = SC0)) +
  geom_point(size = 0.5, color = "blue", alpha = 0.8) +
   scale_x_discrete(breaks = seq(0, 100, by = 5))
```
### Relationship between RecaptchaScore and Score
```{r}
ggplot(data = P2, mapping = aes(x = Q_RecaptchaScore, y = SC0)) +
  geom_point(size = 0.5, color = "blue", alpha = 0.8)
```


### Relationship between "Q4-Q15" and Score

```{r}
library(Hmisc)
describe(P2$Q4)
```


```{r}
ggplot(data = P2) +
   geom_bar(mapping = aes(x = Q4))
```

```{r}
ggplot(data = P2, mapping = aes(x = Q4, y = SC0)) +
  geom_point(size = 0.5, color = "blue", alpha = 0.8)
```

```{r}
ggplot(data = P2, mapping = aes(x = Q4, y = SC0)) +
  geom_boxplot()
```




```{r}
region <- data.frame(location=c("R-1","R-2","R-3","R-4","R-5","R-6"),
				count=c(47,50,21,42,22,17))
region_graph <-ggplot(data=region, aes(x=location, y=count,fill=location))+
geom_bar(stat="identity")
region_graph

```

```{r}
ggplot(data = P2, mapping = aes(x = Q5, y = SC0)) +
 geom_point(size = 0.5, color = "blue", alpha = 0.8)+
  scale_x_discrete(breaks = seq(0, 100, by = 5)) 
```

```{r}
Age <- data.frame(age=c("22-24","25-29","30-34","35-39","40-44"),
				count=c(98,84,10,5,2))

Age_graph <-ggplot(data=Age, aes(x=age, y=count,fill=age))+
geom_bar(stat="identity")
Age_graph
```

```{r}
ggplot(data = P2, mapping = aes(x = Q6, y = SC0)) +
 geom_point(size = 0.5, color = "blue", alpha = 0.8)
```


```{r}
Race <- data.frame(race=c("Whi","AsI","His+Lat","His+Lat+whi","NTS"),
				count=c(153,21,9,7,3))

Race_graph <-ggplot(data=Race, aes(x=race, y=count,fill=race))+
geom_bar(stat="identity")
Race_graph
```

```{r}
ggplot(data = P2, mapping = aes(x = Q7, y = SC0)) +
 geom_point(size = 0.5, color = "blue", alpha = 0.8)+
  scale_x_discrete(breaks = seq(0, 100, by = 5)) 
```

```{r}
ggplot(data = P2) +
   geom_bar(mapping = aes(x = Q8))
```

```{r}
ggplot(data = P2) +
   geom_bar(mapping = aes(x = Q9)) 
```

```{r}
sexual_orientation <- data.frame(so=c("Str","Bi","homo","Que","UN","NTS","As","Pan"),
				count=c(139,28,10,7,4,4,4,3))

sexual_orientation_graph <-ggplot(data=sexual_orientation, aes(x=so, y=count,fill=so))+
geom_bar(stat="identity")
sexual_orientation_graph
```

```{r}
relationship <- data.frame(rela=c("In romantic","Single","Married","divorced"),
				count=c(95,78,24,2))

relationship_graph <-ggplot(data=relationship, aes(x=rela, y=count,fill=rela))+
geom_bar(stat="identity")
relationship_graph
```

```{r}
ggplot(data = P2, mapping = aes(x = Q11, y = SC0)) +
 geom_point(size = 0.5, color = "blue", alpha = 0.8)
```

```{r}
ggplot(data = P2) +
   geom_bar(mapping = aes(x = Q12)) 
```

```{r}
ggplot(data = P2) +
   geom_bar(mapping = aes(x = Q13)) 
```

```{r}
ggplot(data = P2, mapping = aes(x = Q13, y = SC0)) +
 geom_point(size = 0.5, color = "blue", alpha = 0.8)
```

```{r}
ggplot(data = P2) +
   geom_bar(mapping = aes(x = Q14)) 
```

```{r}
Work <- data.frame(work=c("No","<10","10-20","20-30","30-40"),
				count=c(79,70,42,7,1))

Work_graph <-ggplot(data=Work, aes(x=work, y=count,fill=work))+
geom_bar(stat="identity")
Work_graph
```

```{r}
library(readxl)
P3 <- read_excel("D:/MSSP/PESedit 2.xlsx")
```

```{r}
library(tm)
myCorpus <- Corpus(VectorSource(P3))
data_clean <- tm_map(myCorpus,  removeWords, stopwords("english"))
data_clean <- tm_map(data_clean, removeNumbers)
data_clean <- tm_map(data_clean, removePunctuation)
tdm_P3 <- TermDocumentMatrix(data_clean)
inspect(tdm_P3)
```
```{r}
library(stm)
library(topicmodels)
tdm_P4 <- tidy(tdm_P3) %>% 
  cast_dfm(document = document, term = term, value = count)

P4_lda <- stm(tdm_P4, 
              K = 2, 
              verbose = FALSE, 
              init.type = "LDA")
summary(P4_lda)

```

```{r}
tidy(P4_lda)
P4_topics <- tidy(P4_lda, matrix = "beta")
library(ggplot2)
library(dplyr)
tdm_top_terms <- P4_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 10) %>% 
  ungroup() %>%
  arrange(topic, -beta)

tdm_top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()

```

```{r}

```

